### ISSUE TITLE
How to install this into Laravel project?

### ISSUE THREAD

**Issue by newalphamedia** [silktide/wappalyzer-wrapper#30]
I've attempted to install this into my existing Laravel project. I run:

`composer require silktide/wappalyzer-wrapper`

This goes well it seems, but then when I try to execute the examples I get this error:

`message: "Failed to execute. [internal/modules/cjs/loader.js:796↵    throw err;↵    ^↵↵Error: Cannot find module '../node_modules/wappalyzer/wappalyzer'↵Require stack:↵- /home/vagrant/www/testsite/vendor/silktide/wappalyzer-wrapper/src/driver.js↵    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)↵    at Function.Module._load (internal/modules/cjs/loader.js:686:27)↵    at Module.require (internal/modules/cjs/loader.js:848:19)↵    at require (internal/modules/cjs/helpers.js:74:18)↵    at Object.<anonymous> (/home/vagrant/www/testsite/vendor/silktide/wappalyzer-wrapper/src/driver.js:9:20)↵    at Module._compile (internal/modules/cjs/loader.js:955:30)↵    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)↵    at Module.load (internal/modules/cjs/loader.js:811:32)↵    at Function.Module._load (internal/modules/cjs/loader.js:723:14)↵    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10) {↵  code: 'MODULE_NOT_FOUND',↵  requireStack: [↵    '/home/vagrant/www/testsite/vendor/silktide/wappalyzer-wrapper/src/driver.js'↵  ]↵}]"
`

It looks like something perhaps was not installed correctly?

**Comment by newalphamedia** [comment]
Not compatible with Laravel.
